[[pages]]
path = "Balancely.py"
name = "Login"
icon = "âš–ï¸"

[[pages]]
path = "pages/1_Dashboard.py"
name = "Dashboard"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/2_Transaktionen.py"
name = "Transaktionen"
icon = "ğŸ’¸"

[[pages]]
path = "pages/3_Analysen.py"
name = "Analysen"
icon = "ğŸ“‚"

[[pages]]
path = "pages/4_Spartoepfe.py"
name = "SpartÃ¶pfe"
icon = "ğŸª£"

[[pages]]
path = "pages/5_Einstellungen.py"
name = "Einstellungen"
icon = "âš™ï¸"
